### ISSUE TITLE
fix with newer docker ?

### ISSUE THREAD

**Issue by sandys** [calvintam236/docker_xmrig-nvidia#1]
hi,
the newer docker uses `docker run -it --runtime=nvidia` .
Your docker VM does not run with this options and complains of GPU not found. However, I have checked with nvidia-smi docker image as well as servethehome/monero_xmrpooldotnet:nvidia image.

**Comment by calvintam236** [comment]
Hi @sandys, this image is not using `nvidia-docker` base. `--runtime=nvidia` option is only for this base, and did you run with the example command listed in README?

**Comment by sandys** [comment]
Actually thats not accurate. --runtime replaces the need for nvidia-docker.
It also replaces the need for the device mapping that you need to do.

The instructions to use the runtime flag are indeed in the nvidia-docker
GitHub repo, but they are now using the newer runtime system.

**Comment by vnwarrior** [comment]
hi,
sorry to open old bug, but i was also looking for the new --runtime flag. Today you cannot install old docker and must use new docker.
Any chance that you can see if it works with that ? I think your docker base is incompatible. (for example https://github.com/patsissons/xmrig-nvidia-docker/blob/master/Dockerfile)

**Comment by calvintam236** [comment]
Do you think https://hub.docker.com/r/nvidia/cuda/ support your `--runtime` flag?
